"""add customization fields to order_items

Revision ID: 96c7cd855248
Revises: 20260409_002
Create Date: 2026-04-16 01:05:46.303020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c7cd855248'
down_revision: Union[str, None] = '20260409_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('discount_codes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('discount_codes', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('discount_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exchanges', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exchanges', 'status',
               existing_type=postgresql.ENUM('requested', 'approved', 'shipped', 'completed', 'rejected', name='exchange_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operating_costs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('operating_costs', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('order_items', sa.Column('customization_fee_usd', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('customization_file_url', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('customization_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('order_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('order_items', 'qty',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'shipping_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'discount_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'is_free_shipping',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_images', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_images', 'position',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_product_images_variant_position'), table_name='product_images')
    op.create_index(op.f('ix_product_images_variant_id'), 'product_images', ['variant_id'], unique=False)
    op.alter_column('product_variants', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_variants', 'stock_qty',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('product_variants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('product_variants_barcode_key'), 'product_variants', type_='unique')
    op.drop_constraint(op.f('product_variants_sku_key'), 'product_variants', type_='unique')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=True)
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'qty_received',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_po_items_po_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_po_items_variant_id'), table_name='purchase_order_items')
    op.create_index(op.f('ix_purchase_order_items_po_id'), 'purchase_order_items', ['po_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_variant_id'), 'purchase_order_items', ['variant_id'], unique=False)
    op.alter_column('purchase_orders', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=postgresql.ENUM('ordered', 'in_transit', 'received', name='po_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('saved_addresses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('saved_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_saved_addresses_user'), table_name='saved_addresses')
    op.create_index(op.f('ix_saved_addresses_neon_auth_user_id'), 'saved_addresses', ['neon_auth_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_addresses_neon_auth_user_id'), table_name='saved_addresses')
    op.create_index(op.f('ix_saved_addresses_user'), 'saved_addresses', ['neon_auth_user_id'], unique=False)
    op.alter_column('saved_addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('saved_addresses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=postgresql.ENUM('ordered', 'in_transit', 'received', name='po_status'),
               server_default=sa.text("'ordered'::po_status"),
               existing_nullable=False)
    op.alter_column('purchase_orders', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_purchase_order_items_variant_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_po_id'), table_name='purchase_order_items')
    op.create_index(op.f('ix_po_items_variant_id'), 'purchase_order_items', ['variant_id'], unique=False)
    op.create_index(op.f('ix_po_items_po_id'), 'purchase_order_items', ['po_id'], unique=False)
    op.alter_column('purchase_order_items', 'qty_received',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('purchase_order_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=False)
    op.create_unique_constraint(op.f('product_variants_sku_key'), 'product_variants', ['sku'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('product_variants_barcode_key'), 'product_variants', ['barcode'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_variants', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('product_variants', 'stock_qty',
               existing_type=sa.Numeric(precision=10, scale=0),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('product_variants', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_images_variant_id'), table_name='product_images')
    op.create_index(op.f('ix_product_images_variant_position'), 'product_images', ['variant_id', 'position'], unique=False)
    op.alter_column('product_images', 'position',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('product_images', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('orders', 'is_free_shipping',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('orders', 'discount_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('orders', 'shipping_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='payment_status'),
               server_default=sa.text("'pending'::payment_status"),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               server_default=sa.text("'pending'::order_status"),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('order_items', 'qty',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('order_items', 'customization_details')
    op.drop_column('order_items', 'customization_file_url')
    op.drop_column('order_items', 'customization_fee_usd')
    op.alter_column('operating_costs', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('operating_costs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('exchanges', 'status',
               existing_type=postgresql.ENUM('requested', 'approved', 'shipped', 'completed', 'rejected', name='exchange_status'),
               server_default=sa.text("'requested'::exchange_status"),
               existing_nullable=False)
    op.alter_column('exchanges', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('discount_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('discount_codes', 'usage_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('discount_codes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('admin_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('admin_users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
